create schema if not exists den_tasks;

comment on schema den_tasks is
  'Task lifecycle, dependency graph, subtask, availability, and task-history authority.';

create table den_tasks.tasks (
    id bigint generated by default as identity primary key,
    project_id text not null,
    parent_id bigint references den_tasks.tasks(id) on delete cascade,
    title text not null,
    description text,
    status text not null default 'planned',
    priority integer not null default 3,
    assigned_to text,
    tags jsonb,
    blocker_summary text,
    blocker_reason text,
    blocker_attempted_remedies text,
    blocker_suggested_next_step text,
    blocker_requires_human_input boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table den_tasks.task_dependencies (
    task_id bigint not null references den_tasks.tasks(id) on delete cascade,
    depends_on bigint not null references den_tasks.tasks(id) on delete cascade,
    primary key (task_id, depends_on),
    check (task_id <> depends_on)
);

create table den_tasks.task_history (
    id bigint generated by default as identity primary key,
    task_id bigint not null references den_tasks.tasks(id) on delete cascade,
    field text not null,
    old_value text,
    new_value text,
    changed_by text,
    changed_at timestamptz not null default now()
);

create index idx_den_tasks_project_status on den_tasks.tasks(project_id, status);
create index idx_den_tasks_project_parent_priority on den_tasks.tasks(project_id, parent_id, priority, id);
create index idx_den_tasks_assigned on den_tasks.tasks(assigned_to) where assigned_to is not null;
create index idx_den_tasks_parent on den_tasks.tasks(parent_id) where parent_id is not null;
create index idx_den_task_dependencies_depends_on on den_tasks.task_dependencies(depends_on);
create index idx_den_task_history_task_changed on den_tasks.task_history(task_id, changed_at desc, id desc);

comment on table den_tasks.tasks is
  'Canonical task lifecycle rows. Project identity is validated through the projects service, not owned here.';

comment on table den_tasks.task_dependencies is
  'Directed dependency graph: task_id is blocked by depends_on.';

comment on table den_tasks.task_history is
  'Task-local audit history for changed mutable fields.';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_tasks_app') then
        grant usage on schema den_tasks to den_tasks_app;
        grant select, insert, update on den_tasks.tasks to den_tasks_app;
        grant select, insert, delete on den_tasks.task_dependencies to den_tasks_app;
        grant select, insert on den_tasks.task_history to den_tasks_app;
        grant usage, select on all sequences in schema den_tasks to den_tasks_app;
        alter default privileges in schema den_tasks grant select, insert, update on tables to den_tasks_app;
        alter default privileges in schema den_tasks grant usage, select on sequences to den_tasks_app;
    end if;
end $$;
