create table den_tasks.task_change_events (
    id bigint generated by default as identity primary key,
    task_id bigint not null references den_tasks.tasks(id) on delete cascade,
    project_id text not null,
    change_kind text not null,
    changed_at timestamptz not null default now()
);

create index idx_den_task_change_events_project_id on den_tasks.task_change_events(project_id, id);
create index idx_den_task_change_events_task_id on den_tasks.task_change_events(task_id, id desc);

comment on table den_tasks.task_change_events is
  'Monotonic task-list change feed for browser/SSE freshness. Rows are task summary invalidation events, not executable work.';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_tasks_app') then
        grant select, insert on den_tasks.task_change_events to den_tasks_app;
        grant usage, select on all sequences in schema den_tasks to den_tasks_app;
    end if;
end $$;
