create table den_tasks.human_acceptance_reviews (
    id bigint generated by default as identity primary key,
    task_id bigint not null references den_tasks.tasks(id) on delete cascade,
    project_id text not null,
    idempotency_key text not null,
    request_fingerprint text not null,
    reviewer_identity text not null,
    verdict text not null,
    rationale text not null,
    reviewed_revision text,
    reviewed_build text,
    reviewed_environment text,
    evidence_links jsonb not null default '[]'::jsonb,
    lifecycle_effect text not null,
    note_markdown text not null,
    task_status_before text not null,
    task_status_after text not null,
    parent_task_id bigint references den_tasks.tasks(id) on delete set null,
    parent_status_before text,
    parent_status_after text,
    created_at timestamptz not null default now(),
    unique (task_id, idempotency_key)
);

create index idx_den_human_acceptance_task_created
    on den_tasks.human_acceptance_reviews(task_id, created_at desc, id desc);

comment on table den_tasks.human_acceptance_reviews is
  'Immutable human task-acceptance records. These are observation/audit facts and never create or satisfy agent review rounds or GitHub gates.';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_tasks_app') then
        revoke update, delete on den_tasks.human_acceptance_reviews from den_tasks_app;
        grant select, insert on den_tasks.human_acceptance_reviews to den_tasks_app;
        grant usage, select on all sequences in schema den_tasks to den_tasks_app;
    end if;
end $$;
