create schema if not exists den_review;

comment on schema den_review is
  'Review rounds, findings, verdicts, packet validation, and finding response/status authority.';

create table den_review.review_rounds (
    id bigint generated by default as identity primary key,
    project_id text not null,
    task_id bigint not null,
    round_number integer not null,
    requested_by text not null,
    branch text not null,
    base_branch text not null,
    base_commit text not null,
    head_commit text not null,
    last_reviewed_head_commit text,
    commits_since_last_review integer,
    tests_run jsonb,
    notes text,
    preferred_diff_base_ref text,
    preferred_diff_base_commit text,
    preferred_diff_head_ref text,
    preferred_diff_head_commit text,
    alternate_diff_base_ref text,
    alternate_diff_base_commit text,
    alternate_diff_head_ref text,
    alternate_diff_head_commit text,
    delta_base_commit text,
    inherited_commit_count integer,
    task_local_commit_count integer,
    verdict text,
    verdict_by text,
    verdict_notes text,
    requested_at timestamptz not null default now(),
    verdict_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, task_id, round_number)
);

create table den_review.review_findings (
    id bigint generated by default as identity primary key,
    project_id text not null,
    finding_key text not null unique,
    task_id bigint not null,
    review_round_id bigint not null references den_review.review_rounds(id) on delete cascade,
    finding_number integer not null,
    created_by text not null,
    category text not null,
    summary text not null,
    notes text,
    file_references jsonb,
    test_commands jsonb,
    status text not null default 'open',
    status_updated_by text,
    status_notes text,
    status_updated_at timestamptz,
    response_by text,
    response_notes text,
    response_at timestamptz,
    follow_up_task_id bigint,
    run_id text,
    subagent_role text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, task_id, finding_number)
);

create table den_review.review_finding_events (
    id bigint generated by default as identity primary key,
    project_id text not null,
    task_id bigint not null,
    review_round_id bigint not null,
    review_finding_id bigint not null references den_review.review_findings(id) on delete cascade,
    event_kind text not null,
    actor text not null,
    old_status text,
    new_status text,
    notes text,
    response_notes text,
    follow_up_task_id bigint,
    run_id text,
    subagent_role text,
    created_at timestamptz not null default now()
);

create table den_review.review_packets (
    id bigint generated by default as identity primary key,
    project_id text not null,
    task_id bigint not null,
    review_round_id bigint,
    packet_kind text not null,
    sender text not null,
    message_id bigint,
    front_matter jsonb not null,
    typed_envelope jsonb not null,
    markdown_body text not null,
    source_markdown text not null,
    validation_status text not null,
    validation_errors jsonb,
    idempotency_key text,
    created_at timestamptz not null default now(),
    accepted_at timestamptz,
    unique(project_id, idempotency_key)
);

create index review_rounds_project_task_round_idx on den_review.review_rounds(project_id, task_id, round_number);
create index review_rounds_project_task_requested_idx on den_review.review_rounds(project_id, task_id, requested_at desc, id desc);
create index review_findings_project_task_status_idx on den_review.review_findings(project_id, task_id, status);
create index review_findings_round_number_idx on den_review.review_findings(review_round_id, finding_number);
create index review_finding_events_finding_created_idx on den_review.review_finding_events(review_finding_id, created_at, id);
create index review_packets_project_task_created_idx on den_review.review_packets(project_id, task_id, created_at desc, id desc);
create index review_packets_round_kind_created_idx on den_review.review_packets(review_round_id, packet_kind, created_at desc);
create index review_packets_message_idx on den_review.review_packets(message_id) where message_id is not null;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_review_app') then
        grant usage on schema den_review to den_review_app;
        grant select, insert, update on den_review.review_rounds to den_review_app;
        grant select, insert, update on den_review.review_findings to den_review_app;
        grant select, insert on den_review.review_finding_events to den_review_app;
        grant select, insert, update on den_review.review_packets to den_review_app;
        grant usage, select on all sequences in schema den_review to den_review_app;
        alter default privileges in schema den_review grant select, insert, update on tables to den_review_app;
        alter default privileges in schema den_review grant usage, select on sequences to den_review_app;
    end if;
end $$;
