create table den_review.github_check_gates (
    id bigint generated by default as identity primary key,
    project_id text not null,
    task_id bigint not null,
    repository text not null,
    commit_sha text not null,
    ref text not null,
    required_checks jsonb not null,
    status text not null,
    requested_by text not null,
    agent_profile text,
    agent_instance_id text,
    session_key text,
    timeout_at timestamptz not null,
    poll_interval_seconds integer not null,
    next_poll_at timestamptz not null,
    last_checked_at timestamptz,
    completed_at timestamptz,
    status_url text,
    summary text,
    check_runs jsonb,
    failure_summary text,
    evidence_message_status text not null default 'not_required',
    evidence_message_id bigint,
    evidence_message_error text,
    evidence_message_attempted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, task_id, commit_sha)
);

create index github_check_gates_task_status_idx on den_review.github_check_gates(project_id, task_id, status, updated_at desc, id desc);
create index github_check_gates_pending_poll_idx on den_review.github_check_gates(next_poll_at, timeout_at, id) where status = 'pending';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_review_app') then
        grant select, insert, update on den_review.github_check_gates to den_review_app;
        grant usage, select on all sequences in schema den_review to den_review_app;
    end if;
end $$;
