create table den_review.review_finalizations (
    id bigint generated by default as identity primary key,
    project_id text not null,
    task_id bigint not null,
    review_round_id bigint not null references den_review.review_rounds(id) on delete cascade,
    verdict text not null,
    decided_by text not null,
    notes text,
    thread_id bigint,
    run_id text,
    subagent_role text,
    target_task_status text not null,
    packet_id bigint not null references den_review.review_packets(id),
    idempotency_key text not null unique,
    packet_idempotency_key text not null,
    state text not null,
    message_id bigint,
    packet_posted_at timestamptz,
    task_transitioned_at timestamptz,
    completed_at timestamptz,
    last_error_step text,
    last_error text,
    message_attempts integer not null default 0,
    task_transition_attempts integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(review_round_id)
);

create index review_finalizations_project_task_created_idx
    on den_review.review_finalizations(project_id, task_id, created_at desc, id desc);

create index review_finalizations_state_updated_idx
    on den_review.review_finalizations(state, updated_at, id)
    where state <> 'complete';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_review_app') then
        grant select, insert, update on den_review.review_finalizations to den_review_app;
        grant usage, select on all sequences in schema den_review to den_review_app;
    end if;
end $$;
