-- den_core Phase 0 draft schema for den-core SQLite -> shared Postgres migration.
--
-- This schema is intentionally TEMPORARY. During Phase 0 the existing .NET
-- den-core process remains the only writer and keeps its existing route/MCP
-- surfaces. Later Phase 1+ extraction waves move tables out of den_core into
-- per-domain den_* schemas with their own writer services.
--
-- Source inventory:
--   den-core/src/DenCore/Data/DatabaseInitializer.cs
--   den-core/den-core-postgres-phase-0-plan-2026-06
--   den-core/den-core-sqlite-coupling-audit-2026-06
--
-- Drafting choices:
-- * Keep current table names.
-- * Preserve importable integer IDs via GENERATED BY DEFAULT AS IDENTITY.
-- * Store timestamps as timestamptz and JSON-shaped columns as jsonb.
-- * Do not copy SQLite FTS5 virtual tables. Documents/knowledge use tsvector
--   columns + GIN indexes as the placeholder Postgres FTS shape; #3324 owns
--   final ranking/snippet/query behavior.

create extension if not exists pg_trgm;

comment on schema den_core is
  'Temporary Phase 0 Core-owned schema for den-core SQLite to Postgres migration. Not final den-services domain ownership.';

create table den_core.projects (
    id text primary key,
    name text not null,
    kind text not null default 'project' check (kind in ('project','personal','assistant','knowledge_base','system')),
    visibility text not null default 'normal' check (visibility in ('normal','hidden','archived')),
    owner text,
    root_path text,
    description text,
    settings_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table den_core.tasks (
    id bigint generated by default as identity primary key,
    project_id text not null references den_core.projects(id) on delete cascade,
    parent_id bigint references den_core.tasks(id) on delete cascade,
    title text not null,
    description text,
    status text not null default 'planned' check (status in ('planned','in_progress','review','blocked','done','cancelled')),
    priority integer not null default 3 check (priority between 1 and 5),
    assigned_to text,
    tags jsonb,
    blocker_summary text,
    blocker_reason text,
    blocker_attempted_remedies text,
    blocker_suggested_next_step text,
    blocker_requires_human_input boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_tasks_project_status on den_core.tasks(project_id, status);
create index idx_tasks_assigned on den_core.tasks(assigned_to);
create index idx_tasks_parent on den_core.tasks(parent_id);

create table den_core.task_dependencies (
    task_id bigint not null references den_core.tasks(id) on delete cascade,
    depends_on bigint not null references den_core.tasks(id) on delete cascade,
    primary key (task_id, depends_on),
    check (task_id <> depends_on)
);

create table den_core.task_history (
    id bigint generated by default as identity primary key,
    task_id bigint not null references den_core.tasks(id) on delete cascade,
    field text not null,
    old_value text,
    new_value text,
    changed_by text,
    changed_at timestamptz not null default now()
);
create index idx_task_history_task on den_core.task_history(task_id);

create table den_core.messages (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    thread_id bigint references den_core.messages(id) on delete set null,
    sender text not null,
    content text not null,
    intent text not null default 'general' check (intent in ('general','note','status_update','question','answer','handoff','review_request','review_feedback','review_approval','task_ready','task_blocked','notification')),
    metadata jsonb,
    created_at timestamptz not null default now()
);
create index idx_messages_project_task on den_core.messages(project_id, task_id);
create index idx_messages_thread on den_core.messages(thread_id);

create table den_core.message_reads (
    message_id bigint not null references den_core.messages(id) on delete cascade,
    agent text not null,
    read_at timestamptz not null default now(),
    primary key (message_id, agent)
);

create table den_core.documents (
    id bigint generated by default as identity primary key,
    project_id text not null references den_core.projects(id) on delete cascade,
    slug text not null,
    title text not null,
    content text not null,
    doc_type text not null default 'spec' check (doc_type in ('prd','spec','adr','convention','reference','note','memory')),
    visibility text not null default 'normal' check (visibility in ('normal','hidden','archived')),
    tags jsonb,
    summary text,
    search_vector tsvector generated always as (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(content,'') || ' ' || coalesce(tags::text,''))) stored,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, slug)
);
create index idx_documents_project_type on den_core.documents(project_id, doc_type);
create index idx_documents_search_vector on den_core.documents using gin(search_vector);

create table den_core.blackboard_entries (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    content text not null,
    tags jsonb,
    idle_ttl_seconds integer check (idle_ttl_seconds is null or idle_ttl_seconds > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_accessed_at timestamptz not null default now()
);
create index idx_blackboard_updated on den_core.blackboard_entries(updated_at desc, id desc);
create index idx_blackboard_last_accessed on den_core.blackboard_entries(last_accessed_at asc) where idle_ttl_seconds is not null;

create table den_core.agent_sessions (
    agent text primary key,
    project_id text references den_core.projects(id) on delete set null,
    session_id text,
    status text not null default 'active' check (status in ('active','inactive')),
    checked_in_at timestamptz not null default now(),
    last_heartbeat timestamptz not null default now(),
    metadata jsonb
);
create index idx_agent_sessions_project_status on den_core.agent_sessions(project_id, status);

create table den_core.agent_instance_bindings (
    instance_id text primary key,
    project_id text references den_core.projects(id) on delete set null,
    agent_identity text not null,
    agent_family text not null,
    role text,
    transport_kind text not null,
    session_id text,
    status text not null default 'active' check (status in ('active','inactive','degraded')),
    metadata jsonb,
    checked_in_at timestamptz not null default now(),
    last_heartbeat timestamptz not null default now()
);
create index idx_agent_bindings_project_status on den_core.agent_instance_bindings(project_id, status, last_heartbeat desc);
create index idx_agent_bindings_project_role_status on den_core.agent_instance_bindings(project_id, role, status, last_heartbeat desc) where role is not null;
create index idx_agent_bindings_project_agent_status on den_core.agent_instance_bindings(project_id, agent_identity, status, last_heartbeat desc);
create index idx_agent_bindings_session on den_core.agent_instance_bindings(session_id) where session_id is not null;

create table den_core.review_rounds (
    id bigint generated by default as identity primary key,
    task_id bigint not null references den_core.tasks(id) on delete cascade,
    round_number integer not null,
    requested_by text not null,
    branch text not null,
    base_branch text not null,
    base_commit text not null,
    head_commit text not null,
    last_reviewed_head_commit text,
    commits_since_last_review integer,
    tests_run text,
    notes text,
    preferred_diff_base_ref text,
    preferred_diff_base_commit text,
    preferred_diff_head_ref text,
    preferred_diff_head_commit text,
    alternate_diff_base_ref text,
    alternate_diff_base_commit text,
    alternate_diff_head_ref text,
    alternate_diff_head_commit text,
    delta_base_commit text,
    inherited_commit_count integer check (inherited_commit_count is null or inherited_commit_count >= 0),
    task_local_commit_count integer check (task_local_commit_count is null or task_local_commit_count >= 0),
    verdict text check (verdict is null or verdict in ('changes_requested','looks_good','follow_up_needed','blocked_by_dependency')),
    verdict_by text,
    verdict_notes text,
    requested_at timestamptz not null default now(),
    verdict_at timestamptz,
    unique(task_id, round_number)
);
create index idx_review_rounds_task on den_core.review_rounds(task_id, round_number);

create table den_core.review_findings (
    id bigint generated by default as identity primary key,
    finding_key text not null unique,
    task_id bigint not null references den_core.tasks(id) on delete cascade,
    review_round_id bigint not null references den_core.review_rounds(id) on delete cascade,
    finding_number integer not null,
    created_by text not null,
    category text not null check (category in ('blocking_bug','acceptance_gap','test_weakness','follow_up_candidate')),
    summary text not null,
    notes text,
    file_references jsonb,
    test_commands jsonb,
    status text not null default 'open' check (status in ('open','claimed_fixed','verified_fixed','not_fixed','superseded','split_to_follow_up')),
    status_updated_by text,
    status_notes text,
    status_updated_at timestamptz,
    response_by text,
    response_notes text,
    response_at timestamptz,
    follow_up_task_id bigint references den_core.tasks(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(task_id, finding_number)
);
create index idx_review_findings_task_status on den_core.review_findings(task_id, status, finding_number);
create index idx_review_findings_round on den_core.review_findings(review_round_id, finding_number);

create table den_core.dispatch_entries (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    target_agent text not null,
    status text not null default 'pending' check (status in ('pending','approved','rejected','completed','expired')),
    trigger_type text not null check (trigger_type in ('message','task_status')),
    trigger_id bigint not null,
    task_id bigint references den_core.tasks(id) on delete set null,
    summary text,
    context_prompt text,
    context_json jsonb,
    dedup_key text not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    decided_at timestamptz,
    completed_at timestamptz,
    decided_by text,
    completed_by text
);
create index idx_dispatch_status on den_core.dispatch_entries(status);
create index idx_dispatch_project_status on den_core.dispatch_entries(project_id, status);
create unique index idx_dispatch_dedup on den_core.dispatch_entries(dedup_key) where status = 'pending';

create table den_core.agent_stream_entries (
    id bigint generated by default as identity primary key,
    stream_kind text not null check (stream_kind in ('ops','message')),
    event_type text not null,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    thread_id bigint references den_core.messages(id) on delete set null,
    dispatch_id bigint references den_core.dispatch_entries(id) on delete set null,
    sender text not null,
    sender_instance_id text,
    recipient_agent text,
    recipient_role text,
    recipient_instance_id text,
    delivery_mode text not null check (delivery_mode in ('record_only','notify','wake')),
    body text,
    metadata jsonb,
    dedup_key text,
    created_at timestamptz not null default now()
);
create index idx_agent_stream_created on den_core.agent_stream_entries(created_at desc, id desc);
create index idx_agent_stream_project_created on den_core.agent_stream_entries(project_id, created_at desc, id desc);
create index idx_agent_stream_kind_event_created on den_core.agent_stream_entries(stream_kind, event_type, created_at desc, id desc);
create index idx_agent_stream_task_created on den_core.agent_stream_entries(task_id, created_at desc, id desc);
create index idx_agent_stream_dispatch on den_core.agent_stream_entries(dispatch_id);
create index idx_agent_stream_sender_created on den_core.agent_stream_entries(sender, created_at desc, id desc);

create table den_core.channels (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    display_name text not null,
    kind text not null check (kind in ('project_default','project_activity','task_room','ad_hoc','system','dm','small_group')),
    project_id text references den_core.projects(id) on delete cascade,
    space_id text references den_core.projects(id) on delete set null,
    created_by text not null default 'system',
    visibility text not null default 'normal' check (visibility in ('normal','private','archived')),
    settings_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    archived_at timestamptz
);
create unique index idx_channels_project_default_unique on den_core.channels(project_id) where project_id is not null and kind = 'project_default';
create index idx_channels_project_kind on den_core.channels(project_id, kind);

create table den_core.channel_messages (
    id bigint generated by default as identity primary key,
    channel_id bigint not null references den_core.channels(id) on delete cascade,
    sender_type text not null check (sender_type in ('user','agent','system','bridge')),
    sender_identity text not null,
    body text not null,
    message_kind text not null default 'human_text' check (message_kind in ('human_text','agent_text','system_event','mirror_summary','command','command_result')),
    source_kind text check (source_kind is null or source_kind in ('task_message','agent_stream_entry','notification','worker_run','review_round','review_finding','wake_event','external_adapter_message')),
    source_id text,
    summary text,
    deep_link text,
    thread_root_message_id bigint references den_core.channel_messages(id) on delete set null,
    reply_to_message_id bigint references den_core.channel_messages(id) on delete set null,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    edited_at timestamptz,
    deleted_at timestamptz
);
create index idx_channel_messages_channel_created on den_core.channel_messages(channel_id, created_at desc, id desc);
create index idx_channel_messages_source on den_core.channel_messages(source_kind, source_id) where source_kind is not null and source_id is not null;

create table den_core.channel_memberships (
    id bigint generated by default as identity primary key,
    channel_id bigint not null references den_core.channels(id) on delete cascade,
    member_type text not null check (member_type in ('user','agent','role','group')),
    member_identity text not null,
    membership_status text not null default 'active' check (membership_status in ('active','muted','left','banned')),
    wake_policy text not null default 'mentions_only' check (wake_policy in ('never','mentions_only','direct_questions_only','substantive_digest','all_human_messages','all_messages_except_self')),
    can_send boolean not null default true,
    can_react boolean not null default true,
    can_invite boolean not null default false,
    cooldown_seconds integer not null default 0 check (cooldown_seconds >= 0),
    max_auto_replies_per_window integer not null default 0 check (max_auto_replies_per_window >= 0),
    settings_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(channel_id, member_type, member_identity)
);
create index idx_channel_memberships_member on den_core.channel_memberships(member_type, member_identity, membership_status);

create table den_core.channel_reactions (
    id bigint generated by default as identity primary key,
    channel_message_id bigint not null references den_core.channel_messages(id) on delete cascade,
    reactor_type text not null check (reactor_type in ('user','agent','system','bridge')),
    reactor_identity text not null,
    reaction_key text not null,
    created_at timestamptz not null default now(),
    unique(channel_message_id, reactor_type, reactor_identity, reaction_key)
);
create index idx_channel_reactions_message on den_core.channel_reactions(channel_message_id);

create table den_core.agent_runs (
    run_id text primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    review_round_id bigint references den_core.review_rounds(id) on delete set null,
    workspace_id text,
    role text,
    backend text,
    model text,
    sender_instance_id text,
    state text not null default 'unknown' check (state in ('running','retrying','aborting','rerun_requested','rerun_accepted','complete','failed','timeout','aborted','unknown')),
    started_at timestamptz,
    ended_at timestamptz,
    duration_ms bigint,
    pid integer,
    exit_code integer,
    signal text,
    timeout_kind text,
    output_status text,
    infrastructure_failure_reason text,
    infrastructure_warning_reason text,
    artifact_dir text,
    stdout_jsonl_path text,
    stderr_log_path text,
    status_json_path text,
    events_jsonl_path text,
    rerun_of_run_id text,
    fallback_model text,
    fallback_from_model text,
    fallback_from_exit_code integer,
    latest_stream_entry_id bigint references den_core.agent_stream_entries(id) on delete set null,
    started_stream_entry_id bigint references den_core.agent_stream_entries(id) on delete set null,
    heartbeat_count integer not null default 0,
    assistant_output_count integer not null default 0,
    event_count integer not null default 0,
    raw_work_event_count integer not null default 0,
    operator_events_json jsonb,
    last_heartbeat_at timestamptz,
    last_assistant_output_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_agent_runs_project_updated on den_core.agent_runs(project_id, updated_at desc, latest_stream_entry_id desc);
create index idx_agent_runs_task_updated on den_core.agent_runs(task_id, updated_at desc, latest_stream_entry_id desc) where task_id is not null;
create index idx_agent_runs_state_updated on den_core.agent_runs(state, updated_at desc, latest_stream_entry_id desc);

create table den_core.agent_workspaces (
    id text primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    branch text not null,
    worktree_path text not null,
    base_branch text not null,
    base_commit text,
    head_commit text,
    state text not null default 'active' check (state in ('planned','active','review','complete','failed','archived')),
    created_by_run_id text references den_core.agent_runs(run_id) on delete set null,
    dev_server_url text,
    preview_url text,
    cleanup_policy text not null default 'keep' check (cleanup_policy in ('keep','delete_worktree','archive')),
    changed_file_summary text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, task_id, branch)
);
create index idx_agent_workspaces_project_updated on den_core.agent_workspaces(project_id, updated_at desc, id desc);
create index idx_agent_workspaces_task_updated on den_core.agent_workspaces(task_id, updated_at desc, id desc);
create index idx_agent_workspaces_state_updated on den_core.agent_workspaces(state, updated_at desc, id desc);
create index idx_agent_workspaces_created_by_run on den_core.agent_workspaces(created_by_run_id) where created_by_run_id is not null;

create table den_core.desktop_git_snapshots (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    workspace_id text references den_core.agent_workspaces(id) on delete set null,
    root_path text not null,
    scope_key text not null,
    state text not null default 'ok' check (state in ('ok','path_not_visible','not_git_repository','git_error','source_offline','missing')),
    branch text,
    is_detached boolean not null default false,
    head_sha text,
    upstream text,
    ahead integer,
    behind integer,
    dirty_counts jsonb not null default '{}'::jsonb,
    changed_files jsonb not null default '[]'::jsonb,
    warnings jsonb not null default '[]'::jsonb,
    truncated boolean not null default false,
    source_instance_id text not null,
    source_display_name text,
    observed_at timestamptz not null,
    received_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, scope_key)
);
create index idx_desktop_git_snapshots_project_observed on den_core.desktop_git_snapshots(project_id, observed_at desc, id desc);

create table den_core.desktop_diff_snapshots (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    workspace_id text references den_core.agent_workspaces(id) on delete set null,
    root_path text not null,
    path text,
    base_ref text,
    head_ref text,
    diff_key text not null,
    max_bytes integer not null,
    staged boolean not null default false,
    diff text not null,
    truncated boolean not null default false,
    "binary" boolean not null default false,
    warnings jsonb not null default '[]'::jsonb,
    source_instance_id text not null,
    source_display_name text,
    observed_at timestamptz not null,
    received_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, diff_key)
);
create index idx_desktop_diff_snapshots_project_observed on den_core.desktop_diff_snapshots(project_id, observed_at desc, id desc);

create table den_core.desktop_session_snapshots (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    workspace_id text references den_core.agent_workspaces(id) on delete set null,
    session_id text not null,
    parent_session_id text,
    agent_identity text,
    role text,
    current_command text,
    current_phase text,
    title text,
    display_name text,
    cwd text,
    kind text,
    backend text,
    status text,
    started_at timestamptz,
    last_activity_at timestamptz,
    exited_at timestamptz,
    exit_code integer,
    source_display_name text,
    capabilities jsonb,
    recent_activity jsonb,
    child_sessions jsonb,
    control_capabilities jsonb,
    warnings jsonb not null default '[]'::jsonb,
    source_instance_id text not null,
    observed_at timestamptz not null,
    received_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, source_instance_id, session_id)
);
create index idx_desktop_session_snapshots_project_observed on den_core.desktop_session_snapshots(project_id, observed_at desc, id desc);

create table den_core.desktop_session_events (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    workspace_id text references den_core.agent_workspaces(id) on delete set null,
    source_instance_id text not null,
    session_id text not null,
    event_type text not null,
    payload jsonb,
    requested_by text,
    reason text check (reason is null or length(reason) <= 2000),
    observed_at timestamptz not null,
    created_at timestamptz not null default now()
);
create index idx_desktop_session_events_project_created on den_core.desktop_session_events(project_id, created_at desc, id desc);
create index idx_desktop_session_events_session_created on den_core.desktop_session_events(session_id, created_at desc, id desc);

create table den_core.consolidation_topics (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    display_name text not null,
    description text,
    aliases jsonb,
    status text not null default 'active' check (status in ('active','inactive','deprecated')),
    owning_space text references den_core.projects(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_consolidation_topics_status on den_core.consolidation_topics(status);

create table den_core.topic_clip_queue_items (
    id bigint generated by default as identity primary key,
    source_agent text not null,
    source_session_id text,
    source_conversation_id text,
    source_message_id bigint,
    owning_space text references den_core.projects(id) on delete set null,
    canonical_topic_slugs jsonb not null,
    raw_content text not null,
    status text not null default 'pending' check (status in ('pending','claimed','processed','discarded','escalated')),
    claim_key text,
    claimed_at timestamptz,
    claim_expires_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_topic_clips_status_created on den_core.topic_clip_queue_items(status, created_at);
create index idx_topic_clips_claim_key on den_core.topic_clip_queue_items(claim_key) where claim_key is not null;

create table den_core.curation_decisions (
    id bigint generated by default as identity primary key,
    clip_id bigint not null references den_core.topic_clip_queue_items(id) on delete cascade,
    decision text not null check (decision in ('processed','discarded','escalated')),
    reason text,
    decided_by text not null,
    decided_at timestamptz not null default now()
);
create index idx_curation_decisions_clip on den_core.curation_decisions(clip_id);

create table den_core.discussion_threads (
    id bigint generated by default as identity primary key,
    target_type text not null check (target_type in ('document')),
    target_project_id text not null references den_core.projects(id) on delete cascade,
    target_id bigint,
    target_slug text,
    target_anchor text,
    thread_key text not null,
    title text not null,
    status text not null default 'open' check (status in ('open','resolved','archived')),
    created_by text not null,
    summary text,
    resolution_summary text,
    metadata_json jsonb,
    last_comment_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create unique index idx_discussion_threads_unique_target_key on den_core.discussion_threads(target_type, coalesce(target_project_id,''), coalesce(target_slug,''), coalesce(target_id,-1), coalesce(target_anchor,''), coalesce(thread_key,''));

create table den_core.discussion_comments (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references den_core.discussion_threads(id) on delete cascade,
    parent_comment_id bigint references den_core.discussion_comments(id) on delete cascade,
    author_identity text not null,
    body_markdown text not null,
    comment_kind text not null default 'comment' check (comment_kind in ('comment','question','answer','resolution','version_note')),
    status text not null default 'active' check (status in ('active','resolved','hidden','deleted')),
    mentions_json jsonb,
    source_refs_json jsonb,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    edited_at timestamptz,
    updated_at timestamptz not null default now()
);
create index idx_discussion_comments_thread on den_core.discussion_comments(thread_id, created_at asc, id asc);

create table den_core.knowledge_entries (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    summary text,
    body_markdown text not null,
    kind text not null default 'reference' check (kind in ('concept','reference','glossary','convention','service_map','tool_notes','gotcha','architecture_note','migration_note')),
    status text not null default 'draft' check (status in ('draft','reviewed','needs_review','deprecated','archived')),
    curation_state text not null default 'unreviewed_import' check (curation_state in ('unreviewed_import','human_curated','agent_curated','needs_recheck')),
    audience_json jsonb,
    aliases_json jsonb,
    source_refs_json jsonb,
    accuracy_notes text,
    replacement_slug text references den_core.knowledge_entries(slug) on delete set null,
    last_reviewed_at timestamptz,
    review_due_at timestamptz,
    created_by text,
    updated_by text,
    search_vector tsvector generated always as (to_tsvector('english', coalesce(slug,'') || ' ' || coalesce(title,'') || ' ' || coalesce(summary,'') || ' ' || coalesce(body_markdown,''))) stored,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_knowledge_entries_status_kind on den_core.knowledge_entries(status, kind, updated_at desc);
create index idx_knowledge_entries_review_due on den_core.knowledge_entries(review_due_at) where review_due_at is not null and status in ('reviewed','needs_review');
create index idx_knowledge_entries_search_vector on den_core.knowledge_entries using gin(search_vector);

create table den_core.knowledge_entry_tags (
    entry_id bigint not null references den_core.knowledge_entries(id) on delete cascade,
    tag text not null,
    primary key (entry_id, tag)
);
create index idx_knowledge_entry_tags_tag on den_core.knowledge_entry_tags(tag, entry_id);

create table den_core.knowledge_entry_revisions (
    id bigint generated by default as identity primary key,
    entry_id bigint not null references den_core.knowledge_entries(id) on delete cascade,
    revision_number integer not null,
    title text not null,
    summary text,
    body_markdown text not null,
    kind text not null,
    status text not null,
    curation_state text not null,
    tags_json jsonb,
    audience_json jsonb,
    aliases_json jsonb,
    source_refs_json jsonb,
    accuracy_notes text,
    replacement_slug text,
    changed_by text,
    change_note text,
    created_at timestamptz not null default now(),
    unique(entry_id, revision_number)
);

create table den_core.knowledge_entry_links (
    id bigint generated by default as identity primary key,
    from_entry_id bigint not null references den_core.knowledge_entries(id) on delete cascade,
    to_entry_slug text not null,
    link_kind text not null default 'related' check (link_kind in ('related','supersedes','superseded_by','see_also','depends_on')),
    description text,
    created_at timestamptz not null default now(),
    unique(from_entry_id, to_entry_slug, link_kind)
);

create table den_core.agent_guidance_entries (
    id bigint generated by default as identity primary key,
    project_id text not null references den_core.projects(id) on delete cascade,
    document_slug text not null,
    document_project_id text references den_core.projects(id) on delete set null,
    importance text not null default 'important' check (importance in ('required','important')),
    audience text,
    sort_order integer not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, document_project_id, document_slug)
);
create index idx_agent_guidance_project_order on den_core.agent_guidance_entries(project_id, sort_order, id);

create table den_core.collaboration_sessions (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    thread_id bigint references den_core.messages(id) on delete set null,
    title text,
    status text not null default 'active',
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create table den_core.collaboration_turns (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    turn_index integer not null,
    speaker_identity text not null,
    body_markdown text not null,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    unique(session_id, turn_index)
);
create table den_core.collaboration_segments (
    id bigint generated by default as identity primary key,
    turn_id bigint not null references den_core.collaboration_turns(id) on delete cascade,
    segment_index integer not null,
    segment_kind text not null,
    content text not null,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    unique(turn_id, segment_index)
);
create table den_core.collaboration_annotations (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    segment_id bigint references den_core.collaboration_segments(id) on delete cascade,
    annotation_kind text not null,
    body_markdown text not null,
    created_by text not null,
    metadata_json jsonb,
    created_at timestamptz not null default now()
);
create table den_core.collaboration_response_drafts (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    author_identity text not null,
    body_markdown text not null,
    status text not null default 'draft',
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table den_core.worker_pool_members (
    worker_identity text primary key,
    profile_identity text,
    worker_role text,
    pool_member_id text,
    agent_instance_id text,
    status text not null default 'available' check (status in ('available','busy','quarantined','offboarded')),
    capabilities_json jsonb,
    metadata_json jsonb,
    last_heartbeat_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table den_core.worker_assignments (
    id bigint generated by default as identity primary key,
    assignment_id text unique,
    run_id text,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    worker_identity text references den_core.worker_pool_members(worker_identity) on delete set null,
    profile_identity text,
    worker_role text,
    agent_instance_id text,
    state text not null default 'ack' check (state in ('ack','running','checkpoint_waiting','blocked','completed','failed','expired')),
    objective text,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    expires_at timestamptz
);
create index idx_worker_assignments_task_state on den_core.worker_assignments(task_id, state);
create index idx_worker_assignments_worker_state on den_core.worker_assignments(worker_identity, state);

create table den_core.worker_checkpoints (
    id bigint generated by default as identity primary key,
    assignment_id bigint references den_core.worker_assignments(id) on delete cascade,
    run_id text,
    checkpoint_kind text not null,
    status text not null default 'open',
    body_markdown text,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);
create table den_core.checkpoint_responses (
    id bigint generated by default as identity primary key,
    checkpoint_id bigint references den_core.worker_checkpoints(id) on delete cascade,
    responder_identity text not null,
    body_markdown text not null,
    metadata_json jsonb,
    created_at timestamptz not null default now()
);
create table den_core.worker_no_capacity_requests (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    run_id text,
    requested_role text,
    preferred_worker_identity text,
    reason_code text not null,
    candidate_stats_json jsonb,
    request_json jsonb,
    diagnostic_message text,
    created_at timestamptz not null default now()
);
create table den_core.worker_pool_lanes (
    profile_identity text not null,
    worker_role text not null,
    lane_key text,
    desired_count integer not null default 0,
    max_count integer,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (profile_identity, worker_role)
);
create table den_core.orchestrator_leases (
    id bigint generated by default as identity primary key,
    lease_id text not null unique,
    project_id text references den_core.projects(id) on delete set null,
    scope_type text not null,
    scope_id text,
    orchestrator_identity text not null,
    state text not null default 'active' check (state in ('active','released','quarantined','expired','degraded')),
    objective text,
    binding_evidence_json jsonb,
    acquired_at timestamptz not null default now(),
    expires_at timestamptz,
    released_at timestamptz,
    metadata_json jsonb
);

create table den_core.capability_definitions (
    capability_id text primary key,
    owner_project_id text references den_core.projects(id) on delete set null,
    display_name text not null,
    description text,
    status text not null default 'experimental' check (status in ('experimental','active','degraded','disabled')),
    side_effect_level text not null default 'read_only' check (side_effect_level in ('read_only','notification_only','bounded_write','external_write')),
    endpoint_json jsonb,
    input_schema_json jsonb,
    output_schema_json jsonb,
    model_config_json jsonb,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create table den_core.capability_invocations (
    id bigint generated by default as identity primary key,
    capability_id text not null references den_core.capability_definitions(capability_id) on delete cascade,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    invoked_by text not null,
    status text not null default 'pending',
    request_json jsonb,
    response_json jsonb,
    error_message text,
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create table den_core.usage_events (
    id bigint generated by default as identity primary key,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    run_id text,
    provider text,
    model text,
    prompt_tokens bigint,
    completion_tokens bigint,
    total_tokens bigint,
    cost_usd numeric(18,8),
    metadata_json jsonb,
    created_at timestamptz not null default now()
);
create table den_core.pricing_snapshots (
    id bigint generated by default as identity primary key,
    provider text not null,
    model text not null,
    input_price_per_million numeric(18,8),
    output_price_per_million numeric(18,8),
    metadata_json jsonb,
    observed_at timestamptz not null default now(),
    unique(provider, model, observed_at)
);

-- Reset all identity sequences after an import that preserves SQLite integer IDs.
-- This function is intentionally idempotent and should be called by the import
-- tool after COPY/INSERT completes.
create or replace function den_core.reset_identity_sequences_after_import()
returns void
language plpgsql
as $$
declare
    table_name text;
    seq_name text;
begin
    foreach table_name in array array[
        'tasks',
        'task_history',
        'messages',
        'documents',
        'blackboard_entries',
        'review_rounds',
        'review_findings',
        'dispatch_entries',
        'agent_stream_entries',
        'channels',
        'channel_messages',
        'channel_memberships',
        'channel_reactions',
        'desktop_git_snapshots',
        'desktop_diff_snapshots',
        'desktop_session_snapshots',
        'desktop_session_events',
        'consolidation_topics',
        'topic_clip_queue_items',
        'curation_decisions',
        'discussion_threads',
        'discussion_comments',
        'knowledge_entries',
        'knowledge_entry_revisions',
        'knowledge_entry_links',
        'agent_guidance_entries',
        'collaboration_sessions',
        'collaboration_turns',
        'collaboration_segments',
        'collaboration_annotations',
        'collaboration_response_drafts',
        'worker_assignments',
        'worker_checkpoints',
        'checkpoint_responses',
        'worker_no_capacity_requests',
        'orchestrator_leases',
        'capability_invocations',
        'usage_events',
        'pricing_snapshots'
    ]
    loop
        select pg_get_serial_sequence(format('den_core.%I', table_name), 'id') into seq_name;
        if seq_name is not null then
            execute format('select setval(%L, coalesce((select max(id) from den_core.%I), 0) + 1, false)', seq_name, table_name);
        end if;
    end loop;
end;
$$;

comment on function den_core.reset_identity_sequences_after_import() is
  'Call after importing SQLite rows with preserved integer IDs so next generated IDs advance past imported data.';

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_core_app') then
        grant usage on schema den_core to den_core_app;
        grant select, insert, update, delete on all tables in schema den_core to den_core_app;
        grant usage, select on all sequences in schema den_core to den_core_app;
        alter default privileges in schema den_core grant select, insert, update, delete on tables to den_core_app;
        alter default privileges in schema den_core grant usage, select on sequences to den_core_app;
    end if;
end $$;
