-- Align Phase 0 den_core draft tables with current den-core SQLite schema
-- surfaces found by the #3319 import/parity dry run.
--
-- These tables were stale in 001_initial.sql because their Core-owned SQLite
-- shapes continued to evolve while the first Postgres draft was being prepared.
-- Phase 0 is still temporary and Core-owned; this migration preserves current
-- table/column names for import parity rather than introducing final domain
-- service ownership.

drop table if exists den_core.checkpoint_responses cascade;
drop table if exists den_core.worker_checkpoints cascade;
drop table if exists den_core.worker_assignments cascade;
drop table if exists den_core.worker_no_capacity_requests cascade;
drop table if exists den_core.orchestrator_leases cascade;
drop table if exists den_core.worker_pool_lanes cascade;
drop table if exists den_core.worker_pool_members cascade;
drop table if exists den_core.capability_invocations cascade;
drop table if exists den_core.capability_definitions cascade;
drop table if exists den_core.usage_events cascade;
drop table if exists den_core.pricing_snapshots cascade;
drop table if exists den_core.collaboration_response_drafts cascade;
drop table if exists den_core.collaboration_annotations cascade;
drop table if exists den_core.collaboration_segments cascade;
drop table if exists den_core.collaboration_turns cascade;
drop table if exists den_core.collaboration_sessions cascade;

create table den_core.capability_definitions (
    capability_id text primary key,
    display_name text not null,
    description text not null default '',
    owner_project_id text references den_core.projects(id) on delete set null,
    implementation_kind text not null default 'registry_only',
    service_endpoint text,
    http_method text not null default 'POST',
    input_schema_ref text,
    output_schema_ref text,
    input_schema_json jsonb,
    output_schema_json jsonb,
    side_effect_level text not null default 'read_only',
    status text not null default 'experimental',
    default_model_json jsonb,
    fallback_models_json jsonb,
    eval_refs_json jsonb,
    timeout_ms integer not null default 30000,
    max_request_bytes integer not null default 10485760,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_capability_definitions_status on den_core.capability_definitions(status);
create index idx_capability_definitions_side_effect on den_core.capability_definitions(side_effect_level);
create index idx_capability_definitions_owner on den_core.capability_definitions(owner_project_id);

create table den_core.capability_invocations (
    id bigint generated by default as identity primary key,
    invocation_id text not null unique,
    capability_id text not null references den_core.capability_definitions(capability_id) on delete cascade,
    capability_version text,
    caller_agent text,
    caller_project_id text not null references den_core.projects(id) on delete cascade,
    caller_task_id bigint references den_core.tasks(id) on delete set null,
    caller_message_id text,
    caller_surface text,
    input_artifact_refs_json jsonb,
    request_json jsonb,
    request_hash text,
    status text not null,
    started_at timestamptz,
    completed_at timestamptz,
    duration_ms bigint,
    model_provider text,
    model_name text,
    model_version text,
    timings_ms_json jsonb,
    cost_json jsonb,
    output_summary text,
    output_json jsonb,
    output_artifact_refs_json jsonb,
    error_type text,
    error_message text,
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_cap_invocations_invocation on den_core.capability_invocations(invocation_id);
create index idx_cap_invocations_capability on den_core.capability_invocations(capability_id);
create index idx_cap_invocations_caller_project on den_core.capability_invocations(caller_project_id);
create index idx_cap_invocations_status on den_core.capability_invocations(status);
create index idx_cap_invocations_caller_task on den_core.capability_invocations(caller_task_id) where caller_task_id is not null;

create table den_core.collaboration_sessions (
    id bigint generated by default as identity primary key,
    project_id text not null references den_core.projects(id) on delete cascade,
    task_id bigint references den_core.tasks(id) on delete set null,
    message_id bigint references den_core.messages(id) on delete set null,
    agent_stream_entry_id bigint references den_core.agent_stream_entries(id) on delete set null,
    pi_run_id text,
    pi_session_id text,
    desktop_operator_session_id text,
    title text,
    status text not null default 'active',
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_collaboration_sessions_project_updated on den_core.collaboration_sessions(project_id, updated_at desc, id desc);
create index idx_collaboration_sessions_task_updated on den_core.collaboration_sessions(task_id, updated_at desc, id desc) where task_id is not null;
create index idx_collaboration_sessions_message on den_core.collaboration_sessions(message_id) where message_id is not null;
create index idx_collaboration_sessions_agent_stream on den_core.collaboration_sessions(agent_stream_entry_id) where agent_stream_entry_id is not null;

create table den_core.collaboration_turns (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    turn_order integer not null,
    role text,
    source_kind text,
    source_ref text,
    source_label text,
    source_uri text,
    source_context text,
    raw_markdown text not null,
    source_content_hash text not null,
    segmenter_version text not null,
    created_at timestamptz not null default now(),
    unique(session_id, turn_order)
);
create index idx_collaboration_turns_session_order on den_core.collaboration_turns(session_id, turn_order);

create table den_core.collaboration_segments (
    id bigint generated by default as identity primary key,
    turn_id bigint not null references den_core.collaboration_turns(id) on delete cascade,
    sequence_number integer not null,
    segment_hash text not null,
    segment_type text not null,
    raw_markdown text not null,
    text text,
    heading_level integer,
    code_language text,
    created_at timestamptz not null default now(),
    unique(turn_id, sequence_number),
    unique(turn_id, segment_hash)
);
create index idx_collaboration_segments_turn_order on den_core.collaboration_segments(turn_id, sequence_number);

create table den_core.collaboration_annotations (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    turn_id bigint not null references den_core.collaboration_turns(id) on delete cascade,
    segment_id bigint not null references den_core.collaboration_segments(id) on delete cascade,
    segment_hash text not null,
    annotation_type text not null,
    body text,
    created_by text,
    updated_by text,
    revision integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_collaboration_annotations_session_updated on den_core.collaboration_annotations(session_id, updated_at desc, id desc);
create index idx_collaboration_annotations_segment on den_core.collaboration_annotations(segment_id, updated_at desc, id desc);

create table den_core.collaboration_response_drafts (
    id bigint generated by default as identity primary key,
    session_id bigint not null references den_core.collaboration_sessions(id) on delete cascade,
    turn_id bigint references den_core.collaboration_turns(id) on delete set null,
    content text not null,
    created_by text,
    updated_by text,
    revision integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_collaboration_drafts_session_updated on den_core.collaboration_response_drafts(session_id, updated_at desc, id desc);

create table den_core.worker_pool_members (
    worker_identity text primary key,
    profile_identity text not null default '',
    worker_role text,
    display_name text,
    capabilities jsonb,
    status text not null default 'available',
    last_heartbeat timestamptz,
    agent_instance_id text,
    channel_id text,
    session_id text,
    metadata jsonb,
    adapter_instance_id text,
    log_pointer text,
    stale_after_seconds integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_worker_pool_members_status on den_core.worker_pool_members(status, updated_at desc);

create table den_core.worker_assignments (
    id bigint generated by default as identity primary key,
    worker_identity text not null references den_core.worker_pool_members(worker_identity),
    run_id text not null,
    project_id text references den_core.projects(id) on delete set null,
    task_id bigint references den_core.tasks(id) on delete set null,
    role text not null,
    assigned_by text not null,
    state text not null default 'ack',
    latest_checkpoint_id bigint,
    cleanup_evidence text,
    cleanup_recorded_at timestamptz,
    acquired_at timestamptz,
    released_at timestamptz,
    lease_id text,
    profile_identity text,
    lease_kind text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_worker_assignments_worker_state on den_core.worker_assignments(worker_identity, state, updated_at desc);
create index idx_worker_assignments_project_state on den_core.worker_assignments(project_id, state, updated_at desc);
create index idx_worker_assignments_task_state on den_core.worker_assignments(task_id, state, updated_at desc) where task_id is not null;
create index idx_worker_assignments_state_updated on den_core.worker_assignments(state, updated_at desc);

create table den_core.worker_checkpoints (
    id bigint generated by default as identity primary key,
    assignment_id bigint not null references den_core.worker_assignments(id),
    run_id text not null,
    checkpoint_type text not null,
    payload jsonb not null,
    created_at timestamptz not null default now()
);
create index idx_worker_checkpoints_assignment on den_core.worker_checkpoints(assignment_id, created_at desc, id desc);
create index idx_worker_checkpoints_run on den_core.worker_checkpoints(run_id, created_at desc, id desc);

create table den_core.checkpoint_responses (
    id bigint generated by default as identity primary key,
    checkpoint_id bigint not null references den_core.worker_checkpoints(id),
    assignment_id bigint references den_core.worker_assignments(id),
    run_id text not null,
    response_type text not null,
    payload jsonb not null,
    created_at timestamptz not null default now()
);
create index idx_checkpoint_responses_checkpoint on den_core.checkpoint_responses(checkpoint_id, created_at desc, id desc);
create index idx_checkpoint_responses_run on den_core.checkpoint_responses(run_id, created_at desc, id desc);
create index idx_checkpoint_responses_assignment on den_core.checkpoint_responses(assignment_id, created_at desc, id desc) where assignment_id is not null;

create table den_core.worker_no_capacity_requests (
    id bigint generated by default as identity primary key,
    project_id text not null references den_core.projects(id) on delete cascade,
    task_id bigint references den_core.tasks(id) on delete set null,
    role text not null,
    assigned_by text not null,
    run_id text not null,
    profile_identity text,
    worker_role text,
    required_capabilities jsonb,
    preferred_worker_identity text,
    reason_code text not null,
    candidate_details jsonb not null default '{}'::jsonb,
    diagnostic_message text,
    created_at timestamptz not null default now()
);
create index idx_no_capacity_project on den_core.worker_no_capacity_requests(project_id, created_at desc);
create index idx_no_capacity_run on den_core.worker_no_capacity_requests(run_id, created_at desc);

create table den_core.worker_pool_lanes (
    profile_identity text not null,
    worker_role text not null,
    capacity integer not null default 4,
    status text not null default 'active',
    metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (profile_identity, worker_role)
);
create index idx_worker_pool_lanes_status on den_core.worker_pool_lanes(status, updated_at desc);

create table den_core.orchestrator_leases (
    id bigint generated by default as identity primary key,
    lease_id text not null unique,
    lease_kind text not null default 'project_orchestrator',
    scope_type text not null default 'project',
    project_id text references den_core.projects(id) on delete set null,
    channel_id text,
    task_id bigint references den_core.tasks(id) on delete set null,
    workstream_handle text,
    objective text,
    lease_owner text not null,
    orchestrator_identity text not null references den_core.worker_pool_members(worker_identity),
    profile_identity text not null default '',
    display_name text,
    capability_metadata jsonb,
    state text not null default 'leased',
    requested_duration_seconds integer,
    actual_duration_seconds integer,
    lease_expires_at timestamptz,
    renewal_policy text not null default 'deny',
    drain_policy text not null default 'graceful',
    agent_instance_id text,
    adapter_instance_id text,
    session_id text,
    run_id text,
    last_seen_at timestamptz,
    latest_checkpoint_id bigint,
    cleanup_evidence text,
    cleanup_recorded_at timestamptz,
    metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index idx_orchestrator_leases_project on den_core.orchestrator_leases(project_id, state, updated_at desc);
create index idx_orchestrator_leases_orchestrator on den_core.orchestrator_leases(orchestrator_identity, state, updated_at desc);
create index idx_orchestrator_leases_state on den_core.orchestrator_leases(state, updated_at desc);
create index idx_orchestrator_leases_expires on den_core.orchestrator_leases(lease_expires_at, state) where lease_expires_at is not null;
create index idx_orchestrator_leases_lease_kind on den_core.orchestrator_leases(lease_kind, state, updated_at desc);

create table den_core.usage_events (
    id bigint generated by default as identity primary key,
    occurred_at timestamptz not null,
    project_id text not null references den_core.projects(id) on delete cascade,
    task_id bigint references den_core.tasks(id) on delete set null,
    assignment_id bigint,
    run_id text,
    session_id text,
    agent_identity text,
    profile_identity text,
    worker_role text,
    worker_identity text,
    operation_kind text not null,
    provider text not null,
    model text not null,
    model_alias text,
    resolved_model text,
    endpoint_kind text,
    input_tokens bigint,
    output_tokens bigint,
    cache_read_tokens bigint,
    cache_write_tokens bigint,
    reasoning_tokens bigint,
    tool_result_tokens bigint,
    request_count integer not null default 1,
    retry_count integer not null default 0,
    streaming boolean not null default false,
    error_kind text,
    pricing_snapshot_id bigint,
    approximate_cost_micro_cents bigint,
    provenance text,
    adapter_version text,
    raw_usage_source text,
    request_id_hint text,
    created_at timestamptz not null default now()
);
create index idx_usage_events_project_occurred on den_core.usage_events(project_id, occurred_at desc, id desc);
create index idx_usage_events_task_occurred on den_core.usage_events(task_id, occurred_at desc, id desc) where task_id is not null;
create index idx_usage_events_role_occurred on den_core.usage_events(worker_role, occurred_at desc, id desc) where worker_role is not null;
create index idx_usage_events_provider_model on den_core.usage_events(provider, model, occurred_at desc, id desc);
create index idx_usage_events_run on den_core.usage_events(run_id, occurred_at desc, id desc) where run_id is not null;
create index idx_usage_events_pricing_snapshot on den_core.usage_events(pricing_snapshot_id) where pricing_snapshot_id is not null;

create table den_core.pricing_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_label text not null,
    snapshot_version text not null,
    effective_at timestamptz,
    entries_json jsonb not null,
    created_by text,
    notes text,
    created_at timestamptz not null default now()
);
create index idx_pricing_snapshots_version on den_core.pricing_snapshots(snapshot_version, id desc);

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_core_app') then
        grant select, insert, update, delete on all tables in schema den_core to den_core_app;
        grant usage, select on all sequences in schema den_core to den_core_app;
    end if;
end $$;
