create schema if not exists den_guidance;

create table den_guidance.agent_guidance_entries (
    id bigint generated by default as identity primary key,
    project_id text not null,
    document_project_id text not null,
    document_slug text not null,
    importance text not null default 'important',
    audience jsonb,
    sort_order integer not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (project_id, document_project_id, document_slug)
);

create table den_guidance.tool_docs (
    tool_name text not null,
    topic text not null,
    title text not null,
    summary text,
    content_markdown text not null,
    allowed_values jsonb,
    examples jsonb,
    status text not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (tool_name, topic)
);

create table den_guidance.tool_doc_aliases (
    tool_name text not null,
    alias text not null,
    topic text not null,
    created_at timestamptz not null default now(),
    primary key (tool_name, alias),
    foreign key (tool_name, topic)
        references den_guidance.tool_docs(tool_name, topic)
        on delete cascade
);

create index agent_guidance_scope_order_idx
    on den_guidance.agent_guidance_entries(project_id, sort_order, importance, document_project_id, document_slug, id);

create index agent_guidance_document_idx
    on den_guidance.agent_guidance_entries(document_project_id, document_slug);

create index tool_docs_tool_status_idx
    on den_guidance.tool_docs(tool_name, status);

do $$
begin
    if to_regclass('den_core.agent_guidance_entries') is not null then
        insert into den_guidance.agent_guidance_entries(
            id,
            project_id,
            document_project_id,
            document_slug,
            importance,
            audience,
            sort_order,
            notes,
            created_at,
            updated_at
        )
        select
            id,
            project_id,
            document_project_id,
            document_slug,
            importance,
            case
                when nullif(trim(coalesce(audience, '')), '') is null then null
                else to_jsonb(regexp_split_to_array(audience, '\s*,\s*'))
            end,
            sort_order,
            notes,
            created_at,
            updated_at
        from den_core.agent_guidance_entries
        on conflict (project_id, document_project_id, document_slug) do nothing;

        perform setval(
            pg_get_serial_sequence('den_guidance.agent_guidance_entries', 'id'),
            greatest(coalesce((select max(id) from den_guidance.agent_guidance_entries), 1), 1),
            true
        );
    end if;
end $$;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_guidance_app') then
        grant usage on schema den_guidance to den_guidance_app;
        grant select, insert, update, delete on den_guidance.agent_guidance_entries to den_guidance_app;
        grant select, insert, update, delete on den_guidance.tool_docs to den_guidance_app;
        grant select, insert, update, delete on den_guidance.tool_doc_aliases to den_guidance_app;
        grant usage, select on all sequences in schema den_guidance to den_guidance_app;
        alter default privileges in schema den_guidance grant select, insert, update, delete on tables to den_guidance_app;
        alter default privileges in schema den_guidance grant usage, select on sequences to den_guidance_app;
    end if;
end $$;
