-- Contextual applicability only. Canonical entry material remains owned by
-- den_knowledge and is read through its API at resolution time.
create table den_guidance.knowledge_bindings (
    id bigint generated by default as identity primary key,
    target_kind text not null default 'knowledge' check (target_kind = 'knowledge'),
    target_ref text not null check (btrim(target_ref) <> ''),
    scope_kind text not null check (scope_kind in ('global', 'project', 'task', 'agent_profile', 'capability')),
    scope_ref text not null,
    audience jsonb,
    priority integer not null default 0,
    sort_order integer not null default 0,
    read_policy text not null default 'on_demand' check (read_policy in ('inline', 'must_read', 'on_demand', 'latent')),
    read_when text,
    shadows_global boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        (scope_kind = 'global' and scope_ref = '_global' and shadows_global = false)
        or (scope_kind in ('project', 'agent_profile', 'capability') and btrim(scope_ref) <> '' and scope_ref <> '_global')
        or (scope_kind = 'task' and scope_ref ~ '^[1-9][0-9]*$')
    ),
    unique (target_kind, target_ref, scope_kind, scope_ref)
);

create index knowledge_bindings_resolution_idx
    on den_guidance.knowledge_bindings(scope_kind, scope_ref, read_policy, priority desc, sort_order, target_ref, id);

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'den_guidance_app') then
        grant select, insert, update, delete on den_guidance.knowledge_bindings to den_guidance_app;
    end if;
end $$;
